#!/usr/bin/env bash

## Description: Configures local setup
## Usage: setup
## Example: ddev setup

echo "=== Composer install:"
ddev composer install

echo "=== Minimal site install:"
ddev drush si minimal -y --account-name=admin --account-mail=admin@admin.com --account-pass=admin
ddev drush cr

echo "=== Import DB:"
ddev import-db -f ckeditor-5-sandbox.sql.gz
ddev drush updb -y
ddev drush cr

echo "=== Import config:"
ddev drush cim -y
ddev drush cr
ddev drush deploy:hook -y
ddev drush cr
