version: '3.6'

services:
  web:
    ports:
      - "1234"
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,1235:1234
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,1234:1234
  # Keep the database port stable, so external tools can consistently connect.
  db:
    ports:
      - "3312:3306"
